---
  - include_tasks: mysql.yml
    when: zabbix.mysql.deploy
  - include_tasks: server.yml
    when: zabbix.server.deploy
  - include_tasks: proxy.yml
    when: zabbix.proxy.deploy
  - include_tasks: web.yml
    when: zabbix.web.deploy
