---
  - include_tasks: mysql.yml
    when: zabbix.mysql.deploy is true
  - include_tasks: server.yml
    when: zabbix.server.deploy is true
  - include_tasks: proxy.yml
    when: zabbix.proxy.deploy is true
  - include_tasks: web.yml
    when: zabbix.web.deploy is true
