---

- name: Setup mysql container volume
  docker_volume:
    name: mysql_data
    state: present

- name: Setup mysql container container
  docker:
    name: zabbix_mysql
    image: "{{ mysql_container_image }}"
    state: started
    net: host
    pull: always
    env:
      MYSQL_ROOT_PASSWORD: "{{ mysql_password }}"
    volumes:
      - "mysql_data:/var/lib/mysql"
