---

- name: Pull latest mysql container image
  docker_image:
    name: "{{ zabbix.mysql_container_image }}"
    tag: "{{ zabbix.mysql_container_image_tag | default(omit) }}"
    pull: yes
  when: zabbix is defined

- name: Setup mysql container volume
  docker_volume:
    name: mysql_data
    state: present
  when: zabbix is defined

- name: Setup mysql container container
  docker_container:
    name: zabbix_mysql
    image: "{{ zabbix.mysql_container_image }}:{{ zabbix.mysql_container_image_tag | default('latest') }}"
    state: started
    network_mode: host
    restart_policy: "{{ zabbix.mysql_restart_policy | default(omit) }}"
    env:
      MYSQL_ROOT_PASSWORD: "{{ zabbix.mysql_password }}"
    volumes:
      - "mysql_data:/var/lib/mysql"
  when: zabbix is defined
