---

- name: Pull latest zabbix server container image
  docker_image:
    name: "{{ zabbix.server_container_image }}"
    tag: "{{ zabbix.server_container_image_tag | default(omit) }}"
    pull: yes
  when: zabbix is defined

- name: Setup zabbix server container
  docker_container:
    name: zabbix_server
    image: "{{ zabbix.server_container_image }}:{{ zabbix.server_container_image_tag | default('latest') }}"
    state: started
    network_mode: host
    env:
      DB_SERVER_HOST: "{{ ansible_default_ipv4.address }}"
      MYSQL_ROOT_PASSWORD: "{{ zabbix.mysql_password }}"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "{{ zabbix.mysql_password }}"
  when: zabbix is defined
