---

- name: Pull latest zabbix server container image
  docker_image:
    name: "{{ zabbix.server_container_image }}"
    tag: "{{ zabbix.server_container_image_tag | default(omit) }}"
    when: zabbix is defined

- name: Retrieve DB container IP
  docker_image_facts:
    name: "{{ zabbix.mysql_container_name }}"
  when: zabbix is defined
  register: mysql_server

- name: Setup zabbix server container
  docker_container:
    name: zabbix_server
    image: "{{ zabbix.server_container_image }}"
    tag: "{{ zabbix.server_container_image_tag | default(omit) }}"
    state: started
    network_mode: host
    env:
      DB_SERVER_HOST: "{{ mysql_server.ipaddress }}"
      MYSQL_ROOT_PASSWORD: "{{ zabbix.mysql_password }}"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "{{ zabbix.mysql_password }}"
  when: zabbix is defined
