---

- name: Create /etc/zabbix on host
  file:
    path: /etc/zabbix
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Create /etc/zabbix subdirectories
  file:
    path: "/etc/zabbix/{{ item }}"
    owner: root
    group: root
    mode: 0755
    state: directory
  loop:
    - alertscripts
    - externalscripts
    - modules
    - enc
    - ssh_keys
    - ssl/certs
    - ssl/keys
    - ssl/ssl_ca
    - snmptraps
    - mibs
