---

- name: Pull latest zabbix server container image
  docker_image:
    name: "{{ zabbix.server_container_image }}"
    tag: "{{ zabbix.server_container_image_tag | default(omit) }}"
    pull: yes
  when: zabbix is defined

- name: Create /etc/zabbix on host
  file:
    path: /etc/zabbix
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Create /etc/zabbix subdirectories
  file:
    path: "/etc/zabbix/{{ item }}"
    owner: root
    group: root
    mode: 0755
    state: directory
  loop:
    - alertscripts
    - externalscripts
    - modules
    - enc
    - ssh_keys
    - ssl/certs
    - ssl/keys
    - ssl/ssl_ca
    - snmptraps
    - mibs

- name: Setup zabbix server container
  docker_container:
    name: zabbix_server
    image: "{{ zabbix.server_container_image }}:{{ zabbix.server_container_image_tag | default('latest') }}"
    state: started
    network_mode: host
    env:
      DB_SERVER_HOST: "{{ ansible_default_ipv4.address }}"
      MYSQL_ROOT_PASSWORD: "{{ zabbix.mysql_password }}"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "{{ zabbix.mysql_password }}"
    volumes:
      - /etc/zabbix/alertscripts:/usr/lib/zabbix/alertscripts
      - /etc/zabbix/externalscripts:/usr/lib/zabbix/externalscripts
      - /etc/zabbix/modules:/var/lib/zabbix/modules
      - /etc/zabbix/enc:/var/lib/zabbix/enc
      - /etc/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys
      - /etc/zabbix/ssl/certs:/var/lib/zabbix/ssl/certs
      - /etc/zabbix/ssl/keys:/var/lib/zabbix/ssl/keys
      - /etc/zabbix/ssl/ssl_ca:/var/lib/zabbix/ssl/ssl_ca
      - /etc/zabbix/snmptraps:/var/lib/zabbix/snmptraps
      - /etc/zabbix/mibs:/var/lib/zabbix/mibs
  when: zabbix is defined
