---

- name: Pull latest zabbix web container image
  docker_image:
    name: "{{ zabbix.web_container_image }}"
    tag: "{{ zabbix.web_container_image_tag | default(omit) }}"
    when: zabbix is defined

- name: Retrieve DB container IP
  docker_image_facts:
    name: "{{ zabbix.mysql_container_name }}"
  when: zabbix is defined
  register: mysql_server

- name: Retrieve server container IP
  docker_image_facts:
    name: "{{ zabbix.server_container_name }}"
  when: zabbix is defined
  register: zabbix_server

- name: Setup zabbix web container container
  docker_container:
    name: zabbix_web
    image: "{{ zabbix.web_container_image }}"
    tag: "{{ zabbix.web_container_image_tag | default(omit) }}"
    state: started
    network_mode: host
    env:
      MYSQL_PASSWORD: "{{ zabbix.mysql_password }}"
      ZBX_SERVER_HOST: "{{ zabbix_server.ipaddress }}"
      PHP_TZ: "{{ zabbix.PHP_TZ }}"
      DB_SERVER_HOST: "{{ mysql_server.ipaddress }}"
      MYSQL_USER: zabbix
  when: zabbix is defined
