---

- name: Pull latest zabbix web container image
  docker_image:
    name: "{{ zabbix.web_container_image }}"
    tag: "{{ zabbix.web_container_image_tag | default(omit) }}"
    pull: yes
  when: zabbix is defined

- name: Setup zabbix web container container
  docker_container:
    name: zabbix_web
    image: "{{ zabbix.web_container_image }}:{{ zabbix.web_container_image_tag | default('latest') }}"
    state: started
    network_mode: host
    env:
      MYSQL_PASSWORD: "{{ zabbix.mysql_password }}"
      ZBX_SERVER_HOST: "{{ ansible_default_ipv4.address }}"
      PHP_TZ: "{{ zabbix.PHP_TZ }}"
      DB_SERVER_HOST: "{{ ansible_default_ipv4.address }}"
      MYSQL_USER: zabbix
  when: zabbix is defined
